#	@(#)Makefile	6.4 (Berkeley) 7/15/92

.include "../Makefile.g++"

LIB=		driver
SRCS=		input.cc printer.cc
GXXFLAGS+=	-I$(.CURDIR)
NOMAN=		noman
NOPROFILE=	noprofile

.include <bsd.lib.mk>

install:

.SUFFIXES: .cc
