#
# Copyright (c) 1990 The Regents of the University of California.
# All rights reserved.
#
# %sccs.include.redist.sh
#
#	%W% (Berkeley) %G%
#

COMMON_WORDS_FILE?=	/usr/share/misc/eign
DEFAULT_INDEX_DIR?=	/usr/share/dict/papers
DEFAULT_INDEX_NAME?=	Ind
INDEX_SUFFIX?=		".i"
