#	@(#)Makefile	6.5 (Berkeley) 11/14/91

# REMOVED: libXdvi xtotroff
SUBDIR=		libgroff libdriver groff troff tbl eqn pic \
		refer grotty grops grodvi psbb pfbtops tfmtodit \
		devices macros

depend:

.include <bsd.subdir.mk>
