#
# Copyright (c) 1990 The Regents of the University of California.
# All rights reserved.
#
# %sccs.include.redist.sh
#
#	@(#)Makefile	6.1 (Berkeley) 11/13/91
#

PROG=		pfbtops
SRCS=		pfbtops.c

BROKEN_SPOOLER_FLAGS=0

LDADD+=		$(.CURDIR)/../libgroff/obj/libgroff.a

.include "../../Makefile.inc"
.include <bsd.prog.mk>
