.\" This module is believed to contain source code proprietary to AT&T.
.\" Use and redistribution is subject to the Berkeley Software License
.\" Agreement and your Software Agreement with AT&T (Western Electric).
.\"
.\"	@(#)vhel.mac	6.2 (Berkeley) 4/17/91
.\"
.hy 9
.de op
.nr PD 0
.IP \h'1i'\(ci 1i+2
.nr PD .5v
..
.de sh
.IP "\(sq\ \\$1" 1i
..
.de OP
.op \\$1 \\$2 \\$3
..
.de UC
\&\\$3\\s-1\\$1\\s0\\$2\&
..
