#
# Copyright (c) 1991 The Regents of the University of California.
# All rights reserved.
#
# %sccs.include.redist.sh
#
#	@(#)Makefile	6.1 (Berkeley) 11/13/91
#
PROG=           psbb
SRCS=           psbb.c

.include "../../Makefile.inc"
.include <bsd.prog.mk>
